name: Build and Push Docker Image

on:
  push:
    tags:
      - "*"

jobs:
  deploy-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/lanjelin/openaudible-docker
          flavor: latest=true
          tags: |
            type=ref,event=tag
          labels: |
            maintainer=Lanjelin

      - name: Install Docker
        run: curl -fsSL https://get.docker.com | sh

      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
